name: CI
on: 
  push:
    branches:
    - main
jobs:
  buid:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Node
      uses: actions/setup_node@v1
      with: 
        node-version: 14
      
    - name: install dependecies 
      run: yarn
    
    - name: Test
      run: yarn test --coverage

    
